version: "3.8"

volumes:
  mongo_data:

services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/var/lib/mongo/data
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
